# Generated by Django 2.2.12 on 2020-05-31 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=datetime.date(2020, 5, 31)),
        ),
    ]
