# Generated by Django 2.2.12 on 2020-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200531_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=10000)),
                ('news_id', models.CharField(max_length=10000)),
                ('display_name', models.CharField(max_length=10000)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='62020'),
        ),
    ]
