# Generated by Django 2.2.12 on 2020-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200623_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='72020'),
        ),
    ]
