# Generated by Django 2.2.12 on 2020-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='82020'),
        ),
    ]
